name: aad-book
channels:
  - conda-forge
  - pytorch-lts
  - nvidia
  - fastai
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - numba
  - opencv
  - jupyterlab
  - ipywidgets
  - torch=1.8.2
  - torchvision=0.9.2
  - fastai=2.5.0
  - albumentations
  - tqdm
  - pip
  - pip:
    - fastseg==0.1.2
    - pyclothoids
    - jupyter-book
    - pygame
    - imageio
    - imageio-ffmpeg
